name: Maps Data Dashboards
markdown: kramdown
timezone: America/New_York 
title: Maps Data Dashboards
description: Data from loc.gov about online maps from Library of Congress
baseurl: "/loc-maps-dashboard"
github_repo: loc-maps-dashboard
github_username: reliztrent
